server:
  port: 8080

spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://106.14.41.77:3306/tsien_mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: QWer12#$
  jackson:
    default-property-inclusion: non_null # 序列化时候，字段为空时候，key不显示
  servlet:
    multipart: # 文件上传配置
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration: # 配置mybatis答应日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.tsien.mall: debug
  path: logs/
  file: tsien_mall.log



